# Generated by Django 4.1.1 on 2022-09-28 14:16

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='pfp',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_pfp.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 1500], upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='UsersFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users.usersprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follwer', to='users.usersprofile')),
            ],
        ),
    ]
