# Generated by Django 4.0.6 on 2022-10-03 17:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersprofile_pfp_usersfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='pfp',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_pfp.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[150, 150], upload_to='profile_pics'),
        ),
    ]
