# Generated by Django 4.0.6 on 2022-09-27 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('desc', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 9, 27))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersprofile')),
            ],
        ),
    ]
