# Generated by Django 4.0.6 on 2022-10-03 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersprofile_pfp'),
        ('blog', '0003_alter_blogposts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 3)),
        ),
        migrations.CreateModel(
            name='BlogPostsLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersprofile')),
            ],
        ),
    ]
