# Generated by Django 4.1.1 on 2022-10-06 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersprofile_pfp'),
        ('blog', '0004_alter_blogposts_date_blogpostslikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
        migrations.CreateModel(
            name='BlogPostsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersprofile')),
            ],
        ),
    ]
