# Generated by Django 4.1.1 on 2022-10-13 12:26

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blogpostscomment_blogpostscomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='post_images'),
        ),
    ]
