# Generated by Django 4.1.1 on 2022-10-17 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogposts_date_alter_blogposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
    ]
