# Generated by Django 4.1.1 on 2022-10-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_alter_blogposts_date'),
        ('users', '0004_alter_usersprofile_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='users.usersprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersprofile')),
            ],
        ),
    ]
