# Generated by Django 4.1.1 on 2022-10-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogposts_date'),
        ('ajax', '0002_alter_ajaxnotification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxnotification',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts'),
        ),
    ]
